### ISSUE TITLE
Crash while searching commands if empty command name is present

### ISSUE THREAD

**Issue by g0dsCookie** [DarkIrata/WinCommandPalette#10]
# Expected Behavior

Empty (more specifically invalid) command names should be rejected.

# Current Behavior

Empty/Invalid command names doesn't get rejected. Searching for a command will result in a crash, if there is an empty command name.

# Possible Solution

Add checks to `CreateNewCommandViewModel.AddCommand()` and `ManageCommandViewModel.SaveChanges()` to reject invalid command names.

# Steps to Reproduce

1. Add new command with empty name
2. Save and close the options menu
3. Open the command menu
4. Type anything into the searchbox -> Results in a crash

# Context (Environment)
# Detailed Description
# Possible Implementation

**Comment by DarkIrata** [comment]
Fixed with [065a0f7](https://github.com/DarkIrata/WinCommandPalette/commit/065a0f764d2565c56f0ab1b102faaee611de6643).
