### ISSUE TITLE
WCPPlugin.OnCreation() never called

### ISSUE THREAD

**Issue by g0dsCookie** [DarkIrata/WinCommandPalette#8]
# Expected Behavior

WCPPlugin.OnCreation() should be called after the plugin was successfully loaded.

# Current Behavior

WCPPlugin.OnCreation() never gets called by any method.

# Possible Solution

Add the following code to (for example) [PluginHelper.Load()](https://github.com/DarkIrata/WinCommandPalette/blob/master/WinCommandPalette/PluginSystem/PluginHelper.cs#L60)

`wcpPlugin.OnCreation();`

# Steps to Reproduce

Add a MessageBox (or anything else) to any OnCreation() method, compile and run. The MessageBox is never shown.

# Context (Environment)
# Detailed Description
# Possible Implementation

**Comment by DarkIrata** [comment]
Fixed with [a98507f](https://github.com/DarkIrata/WinCommandPalette/commit/a98507fa767506fbd92719a01d33c0725a6e985f). Also renamed OnCreaton to OnLoad
